feat(dashboard) : dashboard, list patients page, calendar page, and appointment page
edgar-care/mobile pull request #31
Opened 2024-01-21 14:46 UTC by SpiritGY

# Description
. Dashboard
. List of patients
. Create patient
. Modification patient
. Delete patient
. Calendar
. Create slot
. Delete slot
. Appointment page
. Cancel appointment
. Update appointment

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-01-21 14:47 UTC, Lucas-COX commented
Task linked: [CU-860t4e5zn Créer un creneau](https://app.clickup.com/t/860t4e5zn)

2024-01-21 15:38 UTC, MarvinFlm commented on medecin_mobile/lib/screens/dashboard/agenda_page.dart
> +
Fait gaffe au espace un seul suffit

2024-01-21 15:41 UTC, MarvinFlm commented on medecin_mobile/lib/screens/dashboard/patientele_page.dart
> +  List<Map<String, dynamic>> patients = [
Pas de code en brut sauf cas exeptionnel ( pas de back )

2024-01-21 15:54 UTC, MarvinFlm requested changes

2024-01-21 15:54 UTC, MarvinFlm commented on medecin_mobile/lib/screens/dashboard/patientele_page.dart
> +                            label: "Feminin",
Féminin

2024-01-21 15:54 UTC, MarvinFlm commented on medecin_mobile/lib/screens/dashboard/patientele_page.dart
> +                  "Vos maladies renseignée",
Vos maladies renseignées

2024-01-21 15:54 UTC, MarvinFlm commented on medecin_mobile/lib/services/slot_service.dart
> +  Logger().i(response.statusCode);
Rien a faire la

2024-01-21 15:54 UTC, MarvinFlm commented on medecin_mobile/lib/widgets/Agenda/Slot_list_three.dart
> +      height: MediaQuery.of(context).size.height * 0.74,
Modify avec Expanded

2024-01-21 15:54 UTC, MarvinFlm commented on medecin_mobile/lib/widgets/Agenda/slot_list.dart
> +    }
essaye de les mettres plutot au debut

2024-01-21 17:04 UTC, lucas-louis requested changes
Pour la patientèle:
- Mauvais espacement entre Maladies/ Traitements et les valeurs sur la vue patient
- Modification patient, les champs doivent être remplis avec les valeurs actuelles du patient
- Ajout de patient: Mauvais titre du drawer + les champs doivent tous être vides

Pour les rdvs:
- Flèche dropdown pas centrée verticalement
- L'entièreté de la carte doit être cliquable

Pour l'agenda:
- On ne doit pas pouvoir appuyer sur le bout "Ouvrir le créneau" si les deux champs ne sont pas remplis
- On peut sélectionner une heure qui est déjà ouverte

2024-01-22 16:02 UTC, lucas-louis requested changes
La page connexion ne fonctionne plus, les champs n'ont pas l'air de se remplir
Connexion impossible donc review bloquée

2024-01-22 18:35 UTC, lucas-louis requested changes
Patientèle (modification patient):
- Modification du patient, les champs taille et poids ne doivent pas inclure l'unité
- ⚠️ Quand on modifie la valeur d'un des champs du patient même sans valider le changement la valeur du champ change
- Pas d'espacement entre le label et les inputs
- Placeholder "Vos maladies", majuscule en trop sur "Maladies"
- Placeholder "Vos traitements" => pas le bon placeholder
- Label "Vos traitements" => "Vos traitements en cours"
- Label des champs ne sont pas en gras
- Bouton "Sexe", le bouton entier doit être cliquable pas seulement le texte

Patientèle (ajout):
- Champ date de naissance doit être en date ou au moins en chiffre pas de texte ⚠️ si en chiffre vérifier qu'on peut quand même inscrire la date correctement ⚠️ 
- Problème de gras sur les labels
- Le bouton "Ajouter un patient" doit avoir un "+" comme sur le bouton "Ajouter un créneau"

Rendez-vous
- Quand le patient est sélectionné (pour afficher le contenu de son dossier médical), il y a trop d'espacement entre "Maladies/ Traitement" et les valeurs

Agenda (ouvrir un créneau):
- Le bouton pour ouvrir le créneau doit être présent, juste pas cliquable

Agenda:
- La date doit être en français
- ⚠️ Comme les cards ouvertes ont une bordure elles sont trop haute (enlever 2px de padding en y)
- On peut sélectionner une heure qui est déjà ouverte

2024-01-23 13:39 UTC, MarvinFlm submitted a review, later dismissed

2024-01-23 15:07 UTC, lucas-louis requested changes
Patientèle (ajout):
- Problème de gras sur les labels

Rendez-vous
- Quand le patient est sélectionné (pour afficher le contenu de son dossier médical), il y a pas assez d'espacement entre "Maladies/ Traitement" et les valeurs (c'est pas le même espacement que avec allergies)

2024-01-23 15:43 UTC, MarvinFlm approved these changes

2024-01-23 15:55 UTC, lucas-louis approved these changes
LGTM

2024-01-23 15:56 UTC, merged