Cu 86bxxf09 page on boarding
edgar-care/mobile pull request #40
Opened 2024-04-09 02:38 UTC by MarvinFlm

# Description

Add an onBoarding to enter the information of the patient

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it.

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have added the needed labels
- [X] I have linked this PR to a clickup task
- [X] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it.

2024-04-14 09:35 UTC, lucas-louis requested changes
Banner:
- Maybe add more padding on the top of the banner => not enough space on screen without native top bar
- The Edgar is not the good one

- Not enough spacing between the steps and the fields
- You need to update the placeholder of inputs
- The button for the sex and the health issues are not well designed
- Missing uppercase on "Oui" and "Non" button
- The bottom button is too small

- There is no error message (like when you try to continue without filling all the inputs)
- The birthdate needs to be locked after the day of today => you can't be born in the future from now
- When you put a birthdate and you change the sex or the health issues, the birthdate is cleared
- The height and the weight needs to be number input and not text input

⚠️ I can't go to the other steps

⚠️ Is the signup page really working!!

2024-04-27 15:20 UTC, lucas-louis requested changes
- I don't think that the signup/ login page are working
- The button for the sex and the health issues are not well designed
- Missing uppercase on "Oui" and "Non" button
- There is no error message (like when you try to continue without filling all the inputs)
- When you put a birthdate and you change the sex or the health issues, the birthdate is cleared
- Once the "previous" button is clicked we can't continue the onboarding
- The doctor step doesn't show anything

2024-05-02 12:50 UTC, lucas-louis requested changes
- The value of the input needs to start with an uppercase by default
- The button for the sex and the health issues are not well designed (no white background?)
- The "Oui" and "Non" buttons do not follow the design
- Missing padding at the bottom (the continue button is too near to the last input)
- The doctor step doesn't show anything (AGAIN)

2024-05-02 16:25 UTC, lucas-louis requested changes
- The value of the input needs to start with an uppercase by default (AGAIN)
- The button for the sex and the health issues are not well designed (no white background?) (AGAIN)
- The "Oui" and "Non" buttons do not follow the design (AGAIN)
- Missing padding at the bottom (the continue button is too near to the last input) (AGAIN)

Doctor selection:
- No error message when clicking on the next button when no doctor is selected
- Is it connected to the backend?

Antecedents:
- Grey square under the button??
- The selection of the antecedents doesn't work
- The modal needs to open when the input is clicked

2024-05-03 21:28 UTC, lucas-louis requested changes
## The register doesn't create an account

Doctor selection:
- No error message when clicking on the next button when no doctor is selected
- The search bar need to filter without "validating" the search (dynamic search)
- Bad icon for the search bar
- Missing label over the search bar
- Too much spacing between the search bar and the doctor cards
- Too big arrow for the doctor cards
- The name of the doctor needs to follow the design
- The address needs to follow the design

Antecedents:
- You can't validate without adding antecedents (if you say that you have antecedents)
- Bad icon on antecedent input
- "Ajoutez" instead of "Ajouter"
- The font weights are not good
- Is there a shadow under the button of the still relevant value?
- "Nom de votre" instead of "Nom du votre"
- Too much padding at the bottom of the drawer
- You can't delete an added antecedent

Treatment
- Bad icon on drawer
- Bad title on drawer
- Bad icon on input
- The font weights are not good
- "Jour de prise" instead of "Jour des prises"
- "Période de prise" instead of "
- Maybe make the day/ period a bit higher
- The medicines selector is really bad:
  - Too big on some screens
  - If I close the keyboard the selector closes
  - I can't scroll in the selector
- You can't add a medicine without at least a period, a day, a quantity and a name
- If you add another medicine, it'll always be the same medicine name at the end
- You can't remove an added medicine
- You can't add an antecedents without information
- The scroll is weird when there is more than one medicine

Displaying the info of added antecedents
- The font weights are not good
- The medicine icon needs to be blue if there is medicines linked to the antecedent
- You can't display the information of the antecedents if there is no medicines linked to it
- Too much spacing between the label and the list of medicines
- You need to add an "s" if there is more than 1 unit of medicine
- The border of the title needs to be 1px width
- Too much spacing between the days and periods
- Is there a shadow under the button of the still relevant value?

2024-05-06 09:05 UTC, lucas-louis requested changes
Doctor selection:
- Too much spacing between the search bar and the doctor cards (good for now)
- Bad font for the address of the doctors

Antecedents:
- Bad font weight for the labels (too thin)
- Title of the modal too bold?
- Placeholder of the add medicine => "Ajouter" instead of "Ajoutez"
- Too much padding at the bottom of the drawer
You can't delete an added antecedent

Treatment
-  "Ajouter" instead of "Ajoutez"
- "Nom de votre" instead of "Nom du votre"
- The medicines selector is really bad:
  - Too big on some screens
  - If I close the keyboard the selector closes
  - I can't scroll in the selector
- If you add another medicine, it'll always be the same medicine name at the end
- The scroll is weird when there is more than one medicine

Displaying the info of added antecedents
- You can't display the information of the antecedents if there is no medicines linked to it
- You need to add an "s" if there is more than 1 unit of medicine
- The border of the title needs to be 1px width

2024-05-07 09:48 UTC, lucas-louis requested changes
Signup page:
- When bad email address, redirected to the onboarding

Informations page:
- Yes/ No button => font weight too bold

Doctor selection:
- Too much spacing between the search bar and the doctor cards (good for now)

Antecedents:
- Bad font weight for the labels (too thin)
- You can't delete an added antecedent
- Yes/ No button => font weight too bold

Treatment:
- ⚠️ When the name of the medicine is too long for the card

Displaying the info of added antecedents
- Yes/ No button => font weight too bold

List of antecedents:
- Bad font weight for the name of the antecedent
- The border is too wide

2024-05-07 16:54 UTC, lucas-louis requested changes
⚠️ If you put a bad medicine name, there is no error messages

2024-05-07 18:08 UTC, lucas-louis submitted a review, later dismissed
LGTM

2024-05-07 18:59 UTC, SpiritGY requested changes

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/models/onboarding.dart
> +    {'name': 'Dr. Edgar', 'address': '1 rue de la paix, 75000 Paris'},
enleve les variables de test

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/models/onboarding.dart
> +                      message: "Completer tout les champs", context: context));
les fautes de labels, "Compléter tous les champs"

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/models/onboarding.dart
> +        "Still_relevant": stillRelevant,
pas de maj a "still_relevant"

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/services/auth.dart
> +  Logger().i(response.body);
logger

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/services/auth.dart
> +    Logger().i(response.body);
logger

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/services/auth.dart
> +    Logger().i(jsonDecode(body));
logger

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/services/auth.dart
> +  await dotenv.load();
faire dans la main

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/services/auth.dart
> +  Logger().i(traitement);
logger

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/services/auth.dart
> +Future<bool> postTraitement(Map<String, dynamic> traitement) async {
???

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/services/auth.dart
> +Future<bool> postMedicalInfo(Map<String, dynamic> traitement) async {
mauvais fichier

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/lib/services/auth.dart
> +Future<List<dynamic>> getAllDoctor() async {
mauvais fichier

2024-05-07 18:59 UTC, SpiritGY commented on patient_mobile/windows/flutter/CMakeLists.txt
a garder ?

2024-05-07 19:11 UTC, lucas-louis submitted a review, later dismissed
LGTM

2024-05-07 19:25 UTC, SpiritGY approved these changes

2024-05-07 19:25 UTC, SpiritGY commented on patient_mobile/lib/screens/register.dart
> +                Logger().i("Email: $email, Password: $password");
logger

2024-05-07 19:28 UTC, SpiritGY approved these changes

2024-05-07 19:28 UTC, lucas-louis approved these changes

2024-05-07 19:33 UTC, SpiritGY approved these changes

2024-05-07 19:34 UTC, lucas-louis approved these changes

2024-05-07 19:34 UTC, merged