feat(patient): document page
edgar-care/mobile pull request #44
Opened 2024-04-22 14:58 UTC by SpiritGY

# Description

adding document page

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

adding new document page
can see all document
can add document
cant delete document

# Checklist

- [x] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-04-22 14:58 UTC, Lucas-COX commented
Task linked: [CU-86by5vduv Page Document patient](https://app.clickup.com/t/86by5vduv)

2024-05-07 17:14 UTC, lucas-louis requested changes
Adding a document;
- Font weight of the title too bold?
- "Type de document" into "Le type de votre document"
- In the type of medecine there is only the "Général" type
- The document is not adding...

2024-05-08 14:21 UTC, lucas-louis submitted a review, later dismissed
LGTM

2024-05-08 18:13 UTC, lucas-louis approved these changes

2024-05-09 14:05 UTC, merged