feat(navigation): adding patient navbar and multipages
edgar-care/mobile pull request #58
Opened 2024-06-26 12:56 UTC by SpiritGY

# Description

adding mulitpage and new navbar for doctor app

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

switch navbar to new version accurate to patient app one
adding multipage navigation for doctoe app

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-07-11 11:50 UTC, lucas-louis requested changes
Navbar:
- It's a bit complicated to click on a tab in the navbar
- The icon has the good size?

"Mes services"
- Uppercase for patients and diagnotics texts
- All the card needs to be clickable and not only the text/ icon

2024-07-20 19:13 UTC, lucas-louis requested changes
Navbar:
- The profile icon is too small
- Can you change the size of the text and use the small size instead?

Services:
- The background doesn't take all the card

2024-07-20 19:13 UTC, lucas-louis commented on medecin_mobile/lib/screens/dashboard/services.dart
> +          child:Container(
Not linted

2024-08-26 19:51 UTC, lucas-louis requested changes
Services:
- The background of each tab doesn't take all the space available so there is a small white background that doesn't take all the available space of the tab
![image](https://github.com/user-attachments/assets/f49f2024-bff8-40cc-9889-63d14cc7ca51)

2024-09-10 18:00 UTC, MarvinFlm approved these changes
Good

2024-09-10 18:00 UTC, merged