Cu 86bzppqyu refont accueil page
edgar-care/mobile pull request #62
Opened 2024-07-23 22:35 UTC by MarvinFlm

# Description

Refont of the accueil page to fit with the current UI

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the needed labels
- [ ] I have linked this PR to a clickup task
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-08-03 08:19 UTC, lucas-louis requested changes
- The green circle needs to be replace by the avatar of the profile
- The divider needs to be thicker
- Not enough spacing between the "Besoin d'un nouveau rdv" et the button
- Not enough spacing between the appointment and the new appointment section

Treatments:
- Bad border radius
- Bad period name "Après-midi" => "Midi"

2024-08-03 08:19 UTC, lucas-louis commented on patient_mobile/lib/screens/dashboard/accueil_page.dart
> +                      doctor: "Dr. Jean Dupont",
Really ??

2024-08-03 08:19 UTC, lucas-louis commented on patient_mobile/lib/screens/dashboard/accueil_page.dart
> +                      onTap: () {},
You need to open a modal when the card is clicked

2024-09-04 21:43 UTC, lucas-louis requested changes
Can't load the info of the patient: got "Erreur lors du chargement des données"

2024-09-07 20:22 UTC, lucas-louis requested changes
- The divider needs to be thicker
- Not enough spacing between the appointment and the new appointment section
- You need to display the firstname not the name of the patient

Treatments:
- Bad border radius
- The name of the period is not good (too small?)
- Bad fontWeight for the medicines
- The checkbox needs to be on the left (not the right)
- The name of the medicine needs to be crossed when the checkbox is checked

2024-09-09 21:26 UTC, lucas-louis requested changes
Treatments;
- The name of the period is not good (too small and too thick)
- The text is not next to the checkbox
- The name of the treatment is too bolded

2024-09-11 16:28 UTC, lucas-louis approved these changes
LGTM

2024-09-11 16:48 UTC, SpiritGY approved these changes

2024-09-11 16:50 UTC, merged