Cu 86c069thr refont splash scren
edgar-care/mobile pull request #64
Opened 2024-09-03 21:46 UTC by MarvinFlm

# Description

Modify the logo used in the app and add a splashcreen in the begining of the app

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the needed labels
- [ ] I have linked this PR to a clickup task
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-09-04 21:49 UTC, lucas-louis requested changes
- The logo doesn't have the good ratio
- The logo is not the good one => you need to use the one with the blue background
- The pro logo is not the good one
- The splash screen hasn't change?

2024-09-07 20:26 UTC, lucas-louis requested changes
- Use the version of the logo with a border radius
- The splashscreen is still the logo inside a white square on a black background...

2024-09-11 19:32 UTC, lucas-louis approved these changes
LGTM

2024-09-11 21:05 UTC, SpiritGY approved these changes

2024-09-11 21:05 UTC, merged