feat(register) : adding register pages
edgar-care/mobile pull request #77
Opened 2024-10-04 17:51 UTC by SpiritGY

# Description

Register pages for medecin app

### Click Up reference

[CU-86c0hjvby](https://[https://app.clickup.com/t/86c0hjvby))

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Adding 2 register pages build like Figmas
adding register services

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-10-06 18:10 UTC, lucas-louis requested changes
- Too much padding at the bottom of the onboarding page
- Can't create a doctor => error "Les identifiants ne correspondent pas" (maybe because the email and password input are not stored?)

2024-10-13 09:34 UTC, lucas-louis requested changes

2024-10-13 09:34 UTC, lucas-louis commented on medecin_mobile/lib/services/login_service.dart
> +  Logger().d(response.body);
🤨

2024-10-13 12:53 UTC, lucas-louis approved these changes
LGTM

2024-10-14 12:40 UTC, MarvinFlm approved these changes
LGTM

2024-10-24 11:22 UTC, merged