Fix Name and firstname inverse
edgar-care/mobile pull request #80
Opened 2024-10-14 14:25 UTC by MarvinFlm

# Description

Fix the name and the first name invers on the onboarding 

### Click Up reference

[[CU-XXXX](https://app.clickup.com/t/XXXX)](https://github.com/edgar-care/mobile/compare/CU-86c0nj1yq_Fix-Champs-inverss-dans-onboarding?expand=1)

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the needed labels
- [ ] I have linked this PR to a clickup task
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-10-15 19:50 UTC, lucas-louis requested changes

2024-10-15 19:50 UTC, lucas-louis commented on patient_mobile/lib/screens/dashboard/accueil_page.dart
> +                    : 'Bonjour, ${infoMedical['name'] != null ? infoMedical["name"].toUpperCase() : 'medical Folder Doesnt work'} !',
Not the good one => `firstname`

2024-10-15 19:50 UTC, lucas-louis commented on patient_mobile/lib/screens/dashboard/chat_page.dart
> +    return 'Dr. ${doctor1['name']} ${doctor1['firstname'].toUpperCase()}';
No need

2024-10-15 19:50 UTC, lucas-louis commented on patient_mobile/lib/screens/dashboard/chat_page.dart
> +            'Dr. ${doctor1['name']} ${doctor1['firstname'].toUpperCase()}');
No need

2024-10-15 19:50 UTC, lucas-louis commented on patient_mobile/lib/screens/dashboard/chat_page.dart
> +    } else {}
Really??

2024-10-15 19:50 UTC, lucas-louis commented on patient_mobile/lib/screens/2fa/account_page.dart
> +                                                  "${widget.infoMedical['name']} ${widget.infoMedical['firstname'].toUpperCase()}",
No need

2024-10-15 19:50 UTC, lucas-louis commented on patient_mobile/lib/screens/dashboard/accueil_page.dart
> +                            "${infoMedical['name'] ?? 'Ne fonctionne'} ${infoMedical['firstname'] != null ? infoMedical["firstname"].toUpperCase() : 'Pas'}",
No need

2024-10-15 19:50 UTC, lucas-louis commented on patient_mobile/lib/widget/navbarplus.dart
> +                                                    "${infoMedical['name']} ${infoMedical['firstname'].toUpperCase()}",
No need

2024-10-15 19:50 UTC, lucas-louis commented on patient_mobile/lib/widget/navbarplus.dart
> +                                                "${infoMedical['name']} ${infoMedical['firstname'].toUpperCase()}",
No need

2024-10-20 09:31 UTC, lucas-louis requested changes

2024-10-20 09:31 UTC, lucas-louis commented on patient_mobile/lib/screens/dashboard/accueil_page.dart
> +                    : 'Bonjour, ${infoMedical['firstname'] != null ? infoMedical["name"].toUpperCase() : 'medical Folder Doesnt work'} !',
No...

2024-10-20 09:32 UTC, lucas-louis requested changes

2024-10-20 09:32 UTC, lucas-louis commented on patient_mobile/lib/screens/dashboard/accueil_page.dart
> +                            "${infoMedical['name'] ?? 'Ne fonctionne'} ${infoMedical['firstname'] != null ? infoMedical["firstname"].toUpperCase() : 'Pas'}",
Still not

2024-10-22 07:25 UTC, lucas-louis approved these changes
LGTM

2024-10-22 13:47 UTC, SpiritGY approved these changes

2024-10-23 12:51 UTC, merged