fix(document): fix modal illustration, fix update name correctly, and…
edgar-care/mobile pull request #87
Opened 2024-11-06 11:02 UTC by SpiritGY

# Description

fix document page for patient app request in pull request #81 

### Click Up reference

[CU-86c0xvamg](https://app.clickup.com/t/86c0xvamg)

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

fix multiple add with the same modal
fix illustration of modals
fix update modal, update the name correctly now

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [x] I have linked this PR to a clickup task
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2024-11-16 10:34 UTC, lucas-louis requested changes

2024-11-16 10:34 UTC, lucas-louis commented on patient_mobile/lib/services/get_files.dart
> +  Logger().d(response.body);
Logger...

2024-11-21 10:22 UTC, lucas-louis approved these changes

2024-11-22 13:30 UTC, MarvinFlm approved these changes

2024-11-22 13:31 UTC, merged